export const knownGlobalImports: Record<string, string> = {
  Column: 'typeorm',
  Entity: 'typeorm',
  OneToMany: 'typeorm',
  PrimaryGeneratedColumn: 'typeorm',
  ManyToMany: 'typeorm',
  ManyToOne: 'typeorm',
  OneToOne: 'typeorm',
  JoinTable: 'typeorm',
  JoinColumn: 'typeorm',
  Index: 'typeorm',
  Unique: 'typeorm',
  CreateDateColumn: 'typeorm',
  UpdateDateColumn: 'typeorm',
};
