export const OPERATOR_MAP: Record<string, string> = {
  _eq: '=',
  _ne: '!=',
  _lt: '<',
  _lte: '<=',
  _gt: '>',
  _gte: '>=',
  _in: 'IN',
  _nin: 'NOT IN',
  _like: 'LIKE',
  _starts_with: 'LIKE',
  _ends_with: 'LIKE',
  _contains: 'LIKE',
  _is_null: 'IS NULL',
};
